# Generated by Django 3.2.18 on 2023-03-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katachi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team_id',
            new_name='team',
        ),
    ]
